name: PyTest

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  pytest:
    name: Run tests with pytest
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: pip install --upgrade pip
        run: pip install --upgrade pip
      - name: pip install pipenv
        run: pip install pipenv
      - name: pipenv install -d
        run: pipenv install -d
      - name: Test
        run: pipenv run pytest
